/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guarderiapokemon.vista;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author ozilb
 */
public class PantallaInicio extends javax.swing.JFrame {
    int posicionOpcion = 1;
    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelVer = new javax.swing.JLabel();
        labelAniadir = new javax.swing.JLabel();
        labelEliminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seleccionarOpcion(evt);
            }
        });

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 204)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        labelVer.setBackground(new java.awt.Color(204, 102, 0));
        labelVer.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        labelVer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVer.setText("VER POKEMON");
        labelVer.setToolTipText("");
        labelVer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(labelVer);

        labelAniadir.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        labelAniadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAniadir.setText("AÑADIR POKEMON");
        jPanel1.add(labelAniadir);

        labelEliminar.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        labelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminar.setText("ELIMINAR POKEMON");
        jPanel1.add(labelEliminar);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarOpcion(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seleccionarOpcion
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            System.out.println("Implementar selección");
        }else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            System.out.println("Implementar selección");
        }
        
    }//GEN-LAST:event_seleccionarOpcion


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAniadir;
    private javax.swing.JLabel labelEliminar;
    private javax.swing.JLabel labelVer;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
