/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guarderiapokemon.vista;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author ozilb
 */
public class PantallaCarga extends javax.swing.JFrame {
    Timer timer;
    /**
     * Creates new form inicio
     */
    public PantallaCarga() {
        initComponents();
        // Cargar la imagen y redimensionarla
        ImageIcon originalIcon = new ImageIcon("./src/guarderiapokemon/images/PokemonLogo.png");
        Image originalImage = originalIcon.getImage();
        Image resizedImage = originalImage.getScaledInstance(labelPokemonLogo.getWidth(), labelPokemonLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);

        // Asignar la imagen redimensionada al JLabel
        labelPokemonLogo.setIcon(resizedIcon);
        
        timer = new Timer(500, (ActionEvent e) -> {
            labelPressButton.setVisible(!labelPressButton.isVisible());
        });

        // Iniciar el parpadeo
        timer.start();

        // Agregar KeyListener para capturar la tecla presionada
        this.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonPressButton(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        labelPokemonLogo = new javax.swing.JLabel();
        labelPressButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        panelInicio.setBackground(java.awt.Color.darkGray);
        panelInicio.setPreferredSize(new java.awt.Dimension(600, 400));
        panelInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonPressButton(evt);
            }
        });

        labelPokemonLogo.setBackground(new java.awt.Color(255, 255, 255));
        labelPokemonLogo.setMinimumSize(new java.awt.Dimension(100, 200));

        labelPressButton.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        labelPressButton.setForeground(new java.awt.Color(255, 255, 255));
        labelPressButton.setText("PRESS BUTTON");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(labelPokemonLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(labelPressButton)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(labelPokemonLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(labelPressButton)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPressButton(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonPressButton
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            labelPressButton.setVisible(true);
            timer.stop(); // Detener el timer
            cargaCompletada();
        }
    }//GEN-LAST:event_botonPressButton

    public void cargaCompletada(){
        ControladorVentanas.instance.abrirCerrarMainView(this, true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPokemonLogo;
    private javax.swing.JLabel labelPressButton;
    private javax.swing.JPanel panelInicio;
    // End of variables declaration//GEN-END:variables
}
